# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import cloud_storage_pb2 as cloud__storage__pb2


GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in cloud_storage_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AuthServiceStub(object):
    """--- Auth & User ---
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Signup = channel.unary_unary(
                '/cloud.AuthService/Signup',
                request_serializer=cloud__storage__pb2.SignupRequest.SerializeToString,
                response_deserializer=cloud__storage__pb2.SignupResponse.FromString,
                _registered_method=True)
        self.Login = channel.unary_unary(
                '/cloud.AuthService/Login',
                request_serializer=cloud__storage__pb2.LoginRequest.SerializeToString,
                response_deserializer=cloud__storage__pb2.LoginResponse.FromString,
                _registered_method=True)
        self.VerifyOTP = channel.unary_unary(
                '/cloud.AuthService/VerifyOTP',
                request_serializer=cloud__storage__pb2.VerifyOTPRequest.SerializeToString,
                response_deserializer=cloud__storage__pb2.VerifyOTPResponse.FromString,
                _registered_method=True)


class AuthServiceServicer(object):
    """--- Auth & User ---
    """

    def Signup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyOTP(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuthServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Signup': grpc.unary_unary_rpc_method_handler(
                    servicer.Signup,
                    request_deserializer=cloud__storage__pb2.SignupRequest.FromString,
                    response_serializer=cloud__storage__pb2.SignupResponse.SerializeToString,
            ),
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=cloud__storage__pb2.LoginRequest.FromString,
                    response_serializer=cloud__storage__pb2.LoginResponse.SerializeToString,
            ),
            'VerifyOTP': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyOTP,
                    request_deserializer=cloud__storage__pb2.VerifyOTPRequest.FromString,
                    response_serializer=cloud__storage__pb2.VerifyOTPResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cloud.AuthService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cloud.AuthService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AuthService(object):
    """--- Auth & User ---
    """

    @staticmethod
    def Signup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloud.AuthService/Signup',
            cloud__storage__pb2.SignupRequest.SerializeToString,
            cloud__storage__pb2.SignupResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloud.AuthService/Login',
            cloud__storage__pb2.LoginRequest.SerializeToString,
            cloud__storage__pb2.LoginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifyOTP(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloud.AuthService/VerifyOTP',
            cloud__storage__pb2.VerifyOTPRequest.SerializeToString,
            cloud__storage__pb2.VerifyOTPResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class FileServiceStub(object):
    """--- File operations ---
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Upload = channel.stream_unary(
                '/cloud.FileService/Upload',
                request_serializer=cloud__storage__pb2.UploadChunk.SerializeToString,
                response_deserializer=cloud__storage__pb2.UploadResponse.FromString,
                _registered_method=True)
        self.DownloadFile = channel.unary_stream(
                '/cloud.FileService/DownloadFile',
                request_serializer=cloud__storage__pb2.DownloadFileRequest.SerializeToString,
                response_deserializer=cloud__storage__pb2.DownloadChunk.FromString,
                _registered_method=True)
        self.DeleteFile = channel.unary_unary(
                '/cloud.FileService/DeleteFile',
                request_serializer=cloud__storage__pb2.DeleteFileRequest.SerializeToString,
                response_deserializer=cloud__storage__pb2.DeleteFileResponse.FromString,
                _registered_method=True)
        self.RestoreFile = channel.unary_unary(
                '/cloud.FileService/RestoreFile',
                request_serializer=cloud__storage__pb2.RestoreFileRequest.SerializeToString,
                response_deserializer=cloud__storage__pb2.RestoreFileResponse.FromString,
                _registered_method=True)
        self.ListFiles = channel.unary_unary(
                '/cloud.FileService/ListFiles',
                request_serializer=cloud__storage__pb2.ListFilesRequest.SerializeToString,
                response_deserializer=cloud__storage__pb2.ListFilesResponse.FromString,
                _registered_method=True)


class FileServiceServicer(object):
    """--- File operations ---
    """

    def Upload(self, request_iterator, context):
        """client-streaming upload (init + chunks)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadFile(self, request, context):
        """server-streaming download
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteFile(self, request, context):
        """soft-delete -> move to trash (does not permanently remove)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RestoreFile(self, request, context):
        """restore a trashed file
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListFiles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FileServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Upload': grpc.stream_unary_rpc_method_handler(
                    servicer.Upload,
                    request_deserializer=cloud__storage__pb2.UploadChunk.FromString,
                    response_serializer=cloud__storage__pb2.UploadResponse.SerializeToString,
            ),
            'DownloadFile': grpc.unary_stream_rpc_method_handler(
                    servicer.DownloadFile,
                    request_deserializer=cloud__storage__pb2.DownloadFileRequest.FromString,
                    response_serializer=cloud__storage__pb2.DownloadChunk.SerializeToString,
            ),
            'DeleteFile': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteFile,
                    request_deserializer=cloud__storage__pb2.DeleteFileRequest.FromString,
                    response_serializer=cloud__storage__pb2.DeleteFileResponse.SerializeToString,
            ),
            'RestoreFile': grpc.unary_unary_rpc_method_handler(
                    servicer.RestoreFile,
                    request_deserializer=cloud__storage__pb2.RestoreFileRequest.FromString,
                    response_serializer=cloud__storage__pb2.RestoreFileResponse.SerializeToString,
            ),
            'ListFiles': grpc.unary_unary_rpc_method_handler(
                    servicer.ListFiles,
                    request_deserializer=cloud__storage__pb2.ListFilesRequest.FromString,
                    response_serializer=cloud__storage__pb2.ListFilesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cloud.FileService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cloud.FileService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FileService(object):
    """--- File operations ---
    """

    @staticmethod
    def Upload(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/cloud.FileService/Upload',
            cloud__storage__pb2.UploadChunk.SerializeToString,
            cloud__storage__pb2.UploadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DownloadFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/cloud.FileService/DownloadFile',
            cloud__storage__pb2.DownloadFileRequest.SerializeToString,
            cloud__storage__pb2.DownloadChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloud.FileService/DeleteFile',
            cloud__storage__pb2.DeleteFileRequest.SerializeToString,
            cloud__storage__pb2.DeleteFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RestoreFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloud.FileService/RestoreFile',
            cloud__storage__pb2.RestoreFileRequest.SerializeToString,
            cloud__storage__pb2.RestoreFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListFiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloud.FileService/ListFiles',
            cloud__storage__pb2.ListFilesRequest.SerializeToString,
            cloud__storage__pb2.ListFilesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class NodeServiceStub(object):
    """--- Node management (gRPC) ---
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterNode = channel.unary_unary(
                '/cloud.NodeService/RegisterNode',
                request_serializer=cloud__storage__pb2.RegisterNodeRequest.SerializeToString,
                response_deserializer=cloud__storage__pb2.RegisterNodeResponse.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/cloud.NodeService/Heartbeat',
                request_serializer=cloud__storage__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=cloud__storage__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.GetNodes = channel.unary_unary(
                '/cloud.NodeService/GetNodes',
                request_serializer=cloud__storage__pb2.GetNodesRequest.SerializeToString,
                response_deserializer=cloud__storage__pb2.GetNodesResponse.FromString,
                _registered_method=True)
        self.RemoveNode = channel.unary_unary(
                '/cloud.NodeService/RemoveNode',
                request_serializer=cloud__storage__pb2.RemoveNodeRequest.SerializeToString,
                response_deserializer=cloud__storage__pb2.RemoveNodeResponse.FromString,
                _registered_method=True)


class NodeServiceServicer(object):
    """--- Node management (gRPC) ---
    """

    def RegisterNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNodes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NodeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterNode': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterNode,
                    request_deserializer=cloud__storage__pb2.RegisterNodeRequest.FromString,
                    response_serializer=cloud__storage__pb2.RegisterNodeResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=cloud__storage__pb2.HeartbeatRequest.FromString,
                    response_serializer=cloud__storage__pb2.HeartbeatResponse.SerializeToString,
            ),
            'GetNodes': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNodes,
                    request_deserializer=cloud__storage__pb2.GetNodesRequest.FromString,
                    response_serializer=cloud__storage__pb2.GetNodesResponse.SerializeToString,
            ),
            'RemoveNode': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveNode,
                    request_deserializer=cloud__storage__pb2.RemoveNodeRequest.FromString,
                    response_serializer=cloud__storage__pb2.RemoveNodeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cloud.NodeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cloud.NodeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NodeService(object):
    """--- Node management (gRPC) ---
    """

    @staticmethod
    def RegisterNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloud.NodeService/RegisterNode',
            cloud__storage__pb2.RegisterNodeRequest.SerializeToString,
            cloud__storage__pb2.RegisterNodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloud.NodeService/Heartbeat',
            cloud__storage__pb2.HeartbeatRequest.SerializeToString,
            cloud__storage__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetNodes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloud.NodeService/GetNodes',
            cloud__storage__pb2.GetNodesRequest.SerializeToString,
            cloud__storage__pb2.GetNodesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloud.NodeService/RemoveNode',
            cloud__storage__pb2.RemoveNodeRequest.SerializeToString,
            cloud__storage__pb2.RemoveNodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class AdminServiceStub(object):
    """--- Admin service (gRPC admin ops) ---
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListUsers = channel.unary_unary(
                '/cloud.AdminService/ListUsers',
                request_serializer=cloud__storage__pb2.ListUsersRequest.SerializeToString,
                response_deserializer=cloud__storage__pb2.ListUsersResponse.FromString,
                _registered_method=True)
        self.DeleteUser = channel.unary_unary(
                '/cloud.AdminService/DeleteUser',
                request_serializer=cloud__storage__pb2.DeleteUserAdminRequest.SerializeToString,
                response_deserializer=cloud__storage__pb2.DeleteUserAdminResponse.FromString,
                _registered_method=True)
        self.UpdateQuota = channel.unary_unary(
                '/cloud.AdminService/UpdateQuota',
                request_serializer=cloud__storage__pb2.UpdateQuotaRequest.SerializeToString,
                response_deserializer=cloud__storage__pb2.UpdateQuotaResponse.FromString,
                _registered_method=True)
        self.PurgeFile = channel.unary_unary(
                '/cloud.AdminService/PurgeFile',
                request_serializer=cloud__storage__pb2.PurgeFileRequest.SerializeToString,
                response_deserializer=cloud__storage__pb2.PurgeFileResponse.FromString,
                _registered_method=True)


class AdminServiceServicer(object):
    """--- Admin service (gRPC admin ops) ---
    """

    def ListUsers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateQuota(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PurgeFile(self, request, context):
        """admin purge a file immediately (force permanent delete)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AdminServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListUsers,
                    request_deserializer=cloud__storage__pb2.ListUsersRequest.FromString,
                    response_serializer=cloud__storage__pb2.ListUsersResponse.SerializeToString,
            ),
            'DeleteUser': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteUser,
                    request_deserializer=cloud__storage__pb2.DeleteUserAdminRequest.FromString,
                    response_serializer=cloud__storage__pb2.DeleteUserAdminResponse.SerializeToString,
            ),
            'UpdateQuota': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateQuota,
                    request_deserializer=cloud__storage__pb2.UpdateQuotaRequest.FromString,
                    response_serializer=cloud__storage__pb2.UpdateQuotaResponse.SerializeToString,
            ),
            'PurgeFile': grpc.unary_unary_rpc_method_handler(
                    servicer.PurgeFile,
                    request_deserializer=cloud__storage__pb2.PurgeFileRequest.FromString,
                    response_serializer=cloud__storage__pb2.PurgeFileResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cloud.AdminService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cloud.AdminService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AdminService(object):
    """--- Admin service (gRPC admin ops) ---
    """

    @staticmethod
    def ListUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloud.AdminService/ListUsers',
            cloud__storage__pb2.ListUsersRequest.SerializeToString,
            cloud__storage__pb2.ListUsersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloud.AdminService/DeleteUser',
            cloud__storage__pb2.DeleteUserAdminRequest.SerializeToString,
            cloud__storage__pb2.DeleteUserAdminResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateQuota(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloud.AdminService/UpdateQuota',
            cloud__storage__pb2.UpdateQuotaRequest.SerializeToString,
            cloud__storage__pb2.UpdateQuotaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PurgeFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cloud.AdminService/PurgeFile',
            cloud__storage__pb2.PurgeFileRequest.SerializeToString,
            cloud__storage__pb2.PurgeFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
